TRAIN:
    model: resnet18
    N: 2
    P: 4
    M: 8
    sparse_optimizer: 1

    workers: 3
    batch_size: 256
    epochs: 120

    lr_mode : cosine
    base_lr: 0.1
    warmup_epochs: 5
    warmup_lr: 0.0
    targetlr : 0.0

    momentum: 0.9
    weight_decay: 0.00005


    print_freq: 100
    model_dir: checkpoint/resnet18_2_4by8

    train_root: /home/ehoffer/Datasets/imagenet/train
    val_root: /home/ehoffer/Datasets/imagenet/val




TEST:
    checkpoint_path : data/pretrained_model/
